name: Build & Push to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/tg-bot:${{ github.sha }}
            ${{ secrets.DOCKERHUB_USERNAME }}/tg-bot:latest

      - name: Update Magic Containers
        uses: BunnyWay/actions/container-update-image@main
        with:
          app_id: ${{ vars.BUNNY_APP_ID }}
          api_key: ${{ secrets.BUNNYNET_API_KEY }}
          container: Container
          image_tag: ${{ github.sha }}
